import type { Plan } from "./types";

// 一个稳定的 id 生成器（默认行程用固定 id，方便对比与分享）
let n = 0;
const id = () => `seed-${n++}`;

export const DEFAULT_PLAN: Plan = {
  title: "北京三日 · 我们的行程",
  subtitle: "5月29日 周五 — 5月31日 周日 · 一起把每一格填满吧",
  days: [
    {
      id: "day-1",
      date: "2026-05-29",
      label: "5月29日",
      weekday: "周五",
      tag: "抵达日",
      items: [
        {
          id: id(),
          start: "09:40",
          title: "航班落地北京",
          location: "机场",
          notes: "取行李 + 出关，预计 10:20 左右能出来。她可以来接我，或者我打车去碰头～",
        },
        {
          id: id(),
          start: "11:00",
          end: "11:45",
          title: "酒店放行李 / 简单收拾",
          notes: "酒店地址待定（填这里）。如果不能提前入住，就先寄存行李。",
        },
        {
          id: id(),
          start: "12:00",
          end: "13:30",
          title: "一起吃午饭（接风）",
          notes: "她来选餐厅吧，想吃她爱吃的。",
        },
        {
          id: id(),
          start: "14:30",
          end: "16:30",
          title: "陶艺体验",
          location: "陶艺工作室（待定）",
          notes: "一起拉坯，各做一只杯子，做好后交换——以后用对方做的杯子喝水。需要提前预约。",
          agreed: false,
        },
        {
          id: id(),
          start: "17:00",
          end: "18:30",
          title: "散步 + 咖啡",
          location: "南锣鼓巷 / 三里屯",
          notes: "消化一下，慢慢逛，随便聊。",
        },
        {
          id: id(),
          start: "18:30",
          end: "20:00",
          title: "晚餐",
        },
        {
          id: id(),
          start: "20:15",
          end: "22:30",
          title: "看电影",
          location: "影院（待定）",
          notes: "提前一起选好片子和场次，把座位订在中间靠后。",
          agreed: false,
        },
      ],
    },
    {
      id: "day-2",
      date: "2026-05-30",
      label: "5月30日",
      weekday: "周六",
      tag: "重点日",
      items: [
        {
          id: id(),
          start: "10:00",
          end: "11:00",
          title: "早午餐 Brunch",
          notes: "不用起太早，睡饱了再出门。",
        },
        {
          id: id(),
          start: "11:30",
          end: "13:00",
          title: "调香体验",
          location: "调香工作室（待定）",
          notes: "一起调一瓶专属香水，互相为对方设计味道，瓶子上写上日期。需要预约。",
          agreed: false,
        },
        {
          id: id(),
          start: "13:15",
          end: "14:30",
          title: "午餐",
        },
        {
          id: id(),
          start: "15:00",
          end: "17:00",
          title: "拼豆",
          location: "手作店 / 咖啡馆",
          notes: "拼一个对方喜欢的图案送给对方，比一比谁拼得好看。",
          agreed: false,
        },
        {
          id: id(),
          start: "17:30",
          end: "19:00",
          title: "看日落 / 散步",
          location: "景山公园 / 什刹海",
          notes: "景山能俯瞰故宫，日落很美；什刹海可以沿湖走。看那天天气定。",
        },
        {
          id: id(),
          start: "19:30",
          end: "21:30",
          title: "浪漫晚餐",
          notes: "这一顿好好吃，提前订位，挑个安静有氛围的地方。",
          agreed: false,
        },
      ],
    },
    {
      id: "day-3",
      date: "2026-05-31",
      label: "5月31日",
      weekday: "周日",
      tag: "离开日 · 21:25 起飞",
      items: [
        {
          id: id(),
          start: "10:00",
          end: "11:00",
          title: "一起吃早餐",
          notes: "慢慢吃，不赶时间。",
        },
        {
          id: id(),
          start: "11:30",
          end: "13:00",
          title: "自由活动 / 逛街",
          notes: "买点小礼物 / 带点北京的特产，留个纪念。",
        },
        {
          id: id(),
          start: "13:00",
          end: "14:30",
          title: "午餐",
        },
        {
          id: id(),
          start: "15:00",
          end: "17:30",
          title: "最后的散步，好好告别",
          location: "公园 / 安静的地方",
          notes: "找个不吵的地方坐坐，把这三天聊一聊，约下次。",
        },
        {
          id: id(),
          start: "18:00",
          title: "出发去机场",
          notes: "21:25 起飞。国内航班建议提前约 2 小时到，留出路上时间——这个时间点按实际机场和路况一起再调。",
        },
        {
          id: id(),
          start: "21:25",
          title: "航班起飞 · 旅程结束",
          notes: "到家给她报平安。",
        },
      ],
    },
  ],
};
